"""Annex IV Compliance Documentation Generator (EU AI Act Art. 11).

Renders a Markdown document covering the Annex IV sections that
Powerbrain can populate from its own runtime state. The remaining
sections (declaration of conformity, harmonised standards, post-market
evaluation specifics) are responsibilities of the *deployer* and are
left as explicit placeholders the deployer fills in.

The generator collects data from four runtime sources, all already
built in earlier B-* items:
- Transparency snapshot (B-41) — models, OPA policies, collections,
  PII config, audit-chain integrity
- Risk health payload (B-44) — live indicator state for the risk
  register entries
- Eval stats + windowed metrics + drift baselines (B-45) — accuracy
  monitoring tables
- Risk register doc (B-44) — concrete Powerbrain risk assessment

The output is intentionally English (Annex IV documents are typically
filed in English in the EU) and Markdown so the deployer can convert
to PDF/DOCX with their tooling of choice.

Public entry point: ``generate_annex_iv_doc(ctx)`` returning the
Markdown string. The MCP tool wrapper handles inline vs file output.
"""

from __future__ import annotations

import asyncio
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


COMPLIANCE_DOC_DIR = os.getenv("COMPLIANCE_DOC_DIR", "/var/lib/powerbrain/compliance")
RISK_REGISTER_PATH = os.getenv("RISK_REGISTER_PATH", "docs/risk-management.md")


@dataclass
class ComplianceDocContext:
    """Bundle of runtime state needed to render the doc.

    Built by ``collect_doc_context`` which delegates to the existing
    helpers in mcp-server/server.py — that keeps the rendering pure
    and unit-testable without spinning up the whole stack.
    """
    transparency:  dict
    health:        dict
    eval_stats:    dict
    risk_register: str
    generated_at:  str


# ── Section renderers ──────────────────────────────────────
# Each renderer is a small pure function so tests can pin individual
# section bodies. The top-level generator joins them in order.

def _render_header(ctx: ComplianceDocContext) -> str:
    version = (ctx.transparency or {}).get("report_version", "unknown")
    return (
        "# EU AI Act Annex IV — Technical Documentation\n\n"
        f"**System:** Powerbrain Context Engine\n"
        f"**Generated:** {ctx.generated_at}\n"
        f"**Report version:** `{version}`\n\n"
        "> This document is generated by Powerbrain's "
        "`generate_compliance_doc` MCP tool. It collects the runtime "
        "state of the deployed instance into the Annex IV template "
        "(EU AI Act Art. 11). Powerbrain itself is not a high-risk AI "
        "system; this document supports the **deployer** in compiling "
        "their own Annex IV submission for the high-risk system that "
        "uses Powerbrain as a context-retrieval building block.\n\n"
        "Sections marked **[Deployer]** must be completed by the "
        "deployer with information that is outside Powerbrain's "
        "scope.\n\n"
        "---\n\n"
    )


def _render_section_1_general(ctx: ComplianceDocContext) -> str:
    t = ctx.transparency or {}
    purpose = t.get("system_purpose", "")
    constraints = t.get("deployment_constraints", []) or []
    out = [
        "## 1. General Description of the AI System\n",
        "### 1.1 Purpose and intended use\n",
        purpose if purpose else "_(not configured)_",
        "\n\n### 1.2 Deployment constraints\n",
    ]
    if constraints:
        out.extend(f"- {c}" for c in constraints)
    else:
        out.append("_(none declared)_")
    out.append(
        "\n\n### 1.3 Provider and deployer roles\n"
        "Powerbrain is delivered as open-source software by the "
        "Powerbrain project. The **deployer** runs the Docker Compose "
        "stack on infrastructure they control and is the data "
        "controller under GDPR. **[Deployer]** insert your "
        "organisation name and contact details here.\n\n"
    )
    return "".join(out)


def _render_section_2_elements(ctx: ComplianceDocContext) -> str:
    t = ctx.transparency or {}
    models = t.get("models", {}) or {}
    opa = t.get("opa", {}) or {}
    collections = t.get("collections", []) or []
    pii = t.get("pii_scanner", {}) or {}

    lines = [
        "## 2. System Elements and Development Process\n",
        "### 2.1 Active models\n",
        "| Component | Name | Provider URL |\n",
        "|---|---|---|\n",
    ]
    for key in ("embedding", "llm", "reranker"):
        m = models.get(key) or {}
        name = m.get("name") or m.get("model") or m.get("backend") or "—"
        url  = m.get("provider_url") or "—"
        lines.append(f"| {key} | `{name}` | `{url}` |\n")

    lines.extend([
        "\n### 2.2 Active OPA policies\n",
        "Powerbrain enforces all access decisions through Open Policy "
        "Agent (OPA). The following Rego packages are loaded at "
        "runtime:\n\n",
    ])
    for p in opa.get("active_policies", []) or []:
        lines.append(f"- `{p}`\n")

    lines.extend([
        "\n### 2.3 Vector collections\n",
        "| Name | Status | Points | Vectors |\n",
        "|---|---|---|---|\n",
    ])
    for c in collections:
        lines.append(
            f"| `{c.get('name', '?')}` | {c.get('status', '—')} | "
            f"{c.get('points', '—')} | {c.get('vectors', '—')} |\n"
        )

    lines.extend([
        "\n### 2.4 PII handling configuration\n",
        f"- Scanner enabled: `{pii.get('scanner_enabled')}`\n",
        f"- Languages: `{pii.get('languages')}`\n",
        f"- Entity types: `{pii.get('entity_types')}`\n",
        "\nPII data is stored using the Sealed Vault dual-storage "
        "pattern: pseudonymised text in Qdrant, originals in the "
        "`pii_vault` PostgreSQL schema with row-level security and "
        "HMAC-token-gated access.\n\n",
    ])
    return "".join(lines)


def _render_section_3_monitoring(ctx: ComplianceDocContext) -> str:
    t = ctx.transparency or {}
    h = ctx.health or {}
    audit = t.get("audit_integrity", {}) or {}

    lines = [
        "## 3. Monitoring, Functioning and Control\n",
        "### 3.1 Audit log integrity (Art. 12)\n",
        f"- Hash chain valid: `{audit.get('valid')}`\n",
        f"- Total entries verified at last check: `{audit.get('total_checked')}`\n",
        "\nAudit entries form a SHA-256 hash chain enforced by a "
        "PostgreSQL `BEFORE INSERT` trigger and an append-only "
        "`BEFORE UPDATE` block. Retention pruning preserves chain "
        "continuity via a checkpoint registry (`audit_archive`).\n\n",
        "### 3.2 Live risk indicators\n",
        f"- Overall status: **{h.get('status', 'unknown')}**\n\n",
    ]
    for ind in (h.get("indicators") or []):
        name = ind.get("name", "?")
        sev  = ind.get("severity", "?")
        val  = ind.get("value")
        lines.append(f"- `{name}`: severity={sev}, value={val}\n")
    lines.append(
        "\n### 3.3 Human oversight (Art. 14)\n"
        "- Global circuit breaker (`POST /circuit-breaker`, admin only) "
        "halts all data-retrieval tools when active\n"
        "- Approval queue (`pending_reviews`) intercepts non-admin "
        "requests for confidential/restricted classifications\n"
        "- Pending reviews expire after the configured timeout via "
        "the `pb-worker` `pending_review_timeout` job\n\n"
    )
    return "".join(lines)


def _render_section_4_accuracy(ctx: ComplianceDocContext) -> str:
    e = ctx.eval_stats or {}
    windowed = e.get("windowed") or []
    drift_baselines = e.get("drift_baselines") or []

    lines = [
        "## 4. Accuracy and Performance Metrics (Art. 15)\n",
        "### 4.1 Aggregate feedback\n",
        f"- Period (days): `{e.get('period_days')}`\n",
        f"- Total feedback: `{e.get('total_feedback')}`\n",
        f"- Average rating: `{e.get('avg_rating')}` / 5\n",
        f"- Satisfaction (rating ≥ 4): `{e.get('satisfaction_pct')}%`\n\n",
        "### 4.2 Windowed metrics\n",
        "Computed by the `v_feedback_windowed` SQL view and refreshed "
        "every 5 minutes by the `pb-worker` `accuracy_metrics_refresh` "
        "job.\n\n",
    ]
    if windowed:
        lines.append("| Window | Collection | Samples | Avg Rating | Empty Rate | Rerank |\n")
        lines.append("|---|---|---|---|---|---|\n")
        for w in windowed:
            lines.append(
                f"| {w.get('window')} | `{w.get('collection')}` | "
                f"{w.get('samples')} | {w.get('avg_rating')} | "
                f"{w.get('empty_rate')} | {w.get('rerank')} |\n"
            )
    else:
        lines.append("_(no feedback collected yet)_\n")

    lines.extend([
        "\n### 4.3 Embedding drift baselines\n",
        "Per-collection deployment-snapshot centroids are stored in "
        "`embedding_reference_set`. Cosine distance from the baseline "
        "is checked against per-collection thresholds in "
        "`data.pb.config.drift.thresholds`.\n\n",
    ])
    if drift_baselines:
        lines.append("| Collection | Seeded At | Samples | Dim |\n")
        lines.append("|---|---|---|---|\n")
        for b in drift_baselines:
            lines.append(
                f"| `{b.get('collection')}` | {b.get('seeded_at')} | "
                f"{b.get('sample_count')} | {b.get('embedding_dim')} |\n"
            )
    else:
        lines.append("_(no baselines seeded yet — first `pb-worker` run will seed them)_\n")
    lines.append("\n")
    return "".join(lines)


def _render_section_5_risk(ctx: ComplianceDocContext) -> str:
    lines = [
        "## 5. Risk Management System (Art. 9)\n",
        "Powerbrain ships a concrete risk register at "
        "`docs/risk-management.md`. The full text is reproduced below "
        "so this Annex IV document is self-contained.\n\n",
        "<details><summary>Show full risk register</summary>\n\n",
        ctx.risk_register or "_(not loaded — see docs/risk-management.md)_",
        "\n\n</details>\n\n",
    ]
    return "".join(lines)


def _render_section_6_changes(ctx: ComplianceDocContext) -> str:
    return (
        "## 6. Relevant Changes Made by the Provider\n"
        "The Powerbrain project tracks all relevant changes in the "
        "open-source git repository. The deployer should pin a "
        "specific commit/tag in production and reference it here.\n\n"
        "**[Deployer]** insert the deployed git revision and a link "
        "to its release notes.\n\n"
    )


def _render_section_7_standards(ctx: ComplianceDocContext) -> str:
    return (
        "## 7. Harmonised Standards Applied\n"
        "Powerbrain uses the following open standards in its "
        "implementation:\n\n"
        "- **OAuth 2.1** (RFC 9700) for client authentication\n"
        "- **Model Context Protocol (MCP)** for agent integration\n"
        "- **Open Policy Agent (OPA) / Rego** for policy enforcement\n"
        "- **OpenTelemetry** (W3C trace context) for distributed tracing\n"
        "- **Prometheus exposition format** for metrics\n"
        "- **JSON Schema (Draft 2020-12)** for OPA data validation\n"
        "- **GDPR Art. 5/9/12/17** alignment for personal-data processing\n\n"
        "Harmonised AI Act standards (currently being finalised by "
        "CEN-CENELEC JTC 21) will be added once published. **[Deployer]** "
        "list any additional standards your high-risk system relies on.\n\n"
    )


def _render_section_8_conformity(ctx: ComplianceDocContext) -> str:
    return (
        "## 8. EU Declaration of Conformity\n"
        "**[Deployer]** This section is the deployer's responsibility "
        "and cannot be auto-generated. It must include the deployer's "
        "identification, the system identifier, the harmonised "
        "standards applied, and a signature from a person authorised "
        "to bind the deployer organisation.\n\n"
    )


def _render_section_9_post_market(ctx: ComplianceDocContext) -> str:
    return (
        "## 9. Post-Market Monitoring\n"
        "Powerbrain provides the following building blocks the "
        "deployer can wire into their post-market monitoring plan:\n\n"
        "- **Audit log export** via `export_audit_log` MCP tool "
        "(JSON or CSV, filterable by time window, agent, or action)\n"
        "- **Hash-chain verification** via `verify_audit_integrity` "
        "and the daily `audit_retention_cleanup` worker job\n"
        "- **Live risk indicators** via `GET /health` "
        "(`Accept: application/json`)\n"
        "- **Transparency report** via `GET /transparency` and the "
        "`get_system_info` MCP tool\n"
        "- **Accuracy windowed metrics** via `get_eval_stats` MCP tool "
        "and the Prometheus gauges `pb_accuracy_*`\n"
        "- **Drift detection** via the `pb-worker` "
        "`accuracy_metrics_refresh` job (5 min interval) writing into "
        "`embedding_reference_set`\n"
        "- **Prometheus + Grafana** monitoring stack with the "
        "`pb-accuracy` dashboard pre-provisioned\n"
        "- **Alerting rules** for chain breaks, OPA outages, drift, "
        "empty result rate, and pending-review timeouts\n\n"
        "**[Deployer]** describe how your operations team consumes "
        "these signals (alerting routes, on-call rotations, incident "
        "response).\n\n"
    )


# ── Top-level renderer ─────────────────────────────────────

SECTION_RENDERERS = (
    _render_header,
    _render_section_1_general,
    _render_section_2_elements,
    _render_section_3_monitoring,
    _render_section_4_accuracy,
    _render_section_5_risk,
    _render_section_6_changes,
    _render_section_7_standards,
    _render_section_8_conformity,
    _render_section_9_post_market,
)


def render_doc(ctx: ComplianceDocContext) -> str:
    """Pure rendering — no I/O. Useful in unit tests."""
    return "".join(r(ctx) for r in SECTION_RENDERERS)


# ── Context collection (delegates to existing server helpers) ──

async def collect_doc_context(
    *,
    transparency_loader,
    health_loader,
    eval_stats_loader,
    risk_register_path: str = RISK_REGISTER_PATH,
) -> ComplianceDocContext:
    """Gather all data needed by the renderer.

    Each loader is an async callable so this function stays decoupled
    from the concrete server.py helpers — the tool wrapper passes
    them in. The four loads run in parallel.
    """
    transparency, health, eval_stats = await asyncio.gather(
        transparency_loader(),
        health_loader(),
        eval_stats_loader(),
    )

    risk_text = ""
    try:
        p = Path(risk_register_path)
        if p.exists():
            risk_text = p.read_text(encoding="utf-8")
    except Exception:
        risk_text = ""

    return ComplianceDocContext(
        transparency=transparency or {},
        health=health or {},
        eval_stats=eval_stats or {},
        risk_register=risk_text,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )


async def generate_annex_iv_doc(
    *,
    transparency_loader,
    health_loader,
    eval_stats_loader,
    output_mode: str = "inline",
    output_dir: str = COMPLIANCE_DOC_DIR,
    risk_register_path: str = RISK_REGISTER_PATH,
) -> dict:
    """Top-level entry point used by the MCP tool wrapper.

    Returns ``{"output_mode", "markdown" | "path", "size_bytes",
    "report_version", "generated_at"}``.

    - ``inline`` (default): the full Markdown is returned in
      ``markdown``.
    - ``file``: the doc is written to ``{output_dir}/annex-iv-{ts}.md``
      and the absolute path is returned in ``path``.
    """
    if output_mode not in ("inline", "file"):
        raise ValueError(f"output_mode must be 'inline' or 'file', got {output_mode!r}")

    ctx = await collect_doc_context(
        transparency_loader=transparency_loader,
        health_loader=health_loader,
        eval_stats_loader=eval_stats_loader,
        risk_register_path=risk_register_path,
    )
    body = render_doc(ctx)
    size = len(body.encode("utf-8"))
    version = (ctx.transparency or {}).get("report_version", "unknown")

    if output_mode == "inline":
        return {
            "output_mode":    "inline",
            "markdown":       body,
            "size_bytes":     size,
            "report_version": version,
            "generated_at":   ctx.generated_at,
        }

    # file mode — keep microseconds in the filename so two doc
    # generations in the same second cannot collide.
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = (
        ctx.generated_at
        .replace(":", "")
        .replace("-", "")
        .replace("+", "p")
        .replace(".", "u")
    )
    path = out_dir / f"annex-iv-{ts}.md"
    path.write_text(body, encoding="utf-8")
    return {
        "output_mode":    "file",
        "path":           str(path.resolve()),
        "size_bytes":     size,
        "report_version": version,
        "generated_at":   ctx.generated_at,
    }
